[package]
name = "rust-programming-nyumon"
version = "0.1.0"
authors = ["Takahito Yamada <d_p.t.a.d.fighter@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
